# Generated by Django 5.1 on 2024-09-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_category_id_alter_produto_id_alter_variacao_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
