# Generated by Django 5.1.5 on 2025-02-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='visivel',
            field=models.BooleanField(default=True),
        ),
    ]
