# Generated by Django 5.1.5 on 2025-02-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
