# Generated by Django 5.1.5 on 2025-02-05 18:14

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_remove_category_parent_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
