# Generated by Django 5.1.5 on 2025-02-11 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_alter_produto_imagem'),
        ('produto', '0010_alter_produto_imagem'),
    ]

    operations = [
    ]
