# Generated by Django 5.1.5 on 2025-02-13 15:34

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0011_merge_20250211_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.subcategory'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='visivel',
            field=models.BooleanField(default=True),
        ),
    ]
